urls = {
    'Romance': 'https://www.allfreenovel.com/Book/Category/1/Romance',
    'Erotic': 'https://www.allfreenovel.com/Book/Category/13/Erotic',
    'Adult': 'https://www.allfreenovel.com/Book/Category/15/Adult',
    'Fantasy': 'https://www.allfreenovel.com/Book/Category/3/Fantasy',
    'Billionaire Romance': 'https://www.allfreenovel.com/Book/Category/2/Billionaire%20Romance',
    'New Adult': 'https://www.allfreenovel.com/Book/Category/19/New%20Adult',
    'Paranormal': 'https://www.allfreenovel.com/Book/Category/24/Paranormal',
    'Suspense': 'https://www.allfreenovel.com/Book/Category/9/Suspense',
    'Young Adult': 'https://www.allfreenovel.com/Book/Category/11/Young%20Adult',
    'Fiction': 'https://www.allfreenovel.com/Book/Category/23/Fiction',
    'Crime': 'https://www.allfreenovel.com/Book/Category/14/Crime',
    'Mystery': 'https://www.allfreenovel.com/Book/Category/22/Mystery',
    'Historical': 'https://www.allfreenovel.com/Book/Category/12/Historical',
    'Dark': 'https://www.allfreenovel.com/Book/Category/27/Dark',
    'Thriller': 'https://www.allfreenovel.com/Book/Category/6/Thriller',
    'Vampires': 'https://www.allfreenovel.com/Book/Category/4/Vampires',
    'Science Fiction': 'https://www.allfreenovel.com/Book/Category/5/Science%20Fiction',
    'Sports': 'https://www.allfreenovel.com/Book/Category/20/Sports',
    'M-M Romance': 'https://www.allfreenovel.com/Book/Category/28/M-M%20Romance',
    'Horror': 'https://www.allfreenovel.com/Book/Category/7/Horror',
    'Biker': 'https://www.allfreenovel.com/Book/Category/21/Biker',
    'Western': 'https://www.allfreenovel.com/Book/Category/18/Western',
    'Adventure': 'https://www.allfreenovel.com/Book/Category/25/Adventure',
    'MC': 'https://www.allfreenovel.com/Book/Category/29/MC',
    'Classics': 'https://www.allfreenovel.com/Book/Category/8/Classics',
    'Action': 'https://www.allfreenovel.com/Book/Category/16/Action',
    'Humorous': 'https://www.allfreenovel.com/Book/Category/17/Humorous',
    'Lesbian Romance': 'https://www.allfreenovel.com/Book/Category/30/Lesbian%20Romance'
}
